# ====================================================
# Basic server security & setup
# ====================================================

- name:   Update APT package cache
  action: apt update_cache=yes

- name: install essential packages
  apt: pkg={{ item }} state=latest
  become: true
  with_items:
    - build-essential
    - git-core
    - python-setuptools
    - python-software-properties
    - python-pip
    - aptitude
    - fail2ban
    - unattended-upgrades
    - vim

- name: install other packages
  apt: pkg={{ item }} state=latest
  become: true
  with_items: "{{ additional_packages_to_install }}"
  when: additional_packages_to_install is defined

- name: Upgrade all packages
  apt: upgrade=safe

- name: Adjust APT update intervals
  copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: Restart ssh

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: Restart ssh
